imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        enabled: false
    session:
        save_path: /dev/shm/powerline/%kernel.environment%

monolog:
    handlers:
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: [!event]
            max_files: 10
        push:
            type:  stream
            path:  %kernel.logs_dir%/push_%kernel.environment%.log
            level: debug
            channels: [push]
        slack:
            type: slack
            token: '%slack_logger_token%'
            channel: "#errors"
            level: critical
            excluded_404s:
                - ^/

assetic:
    use_controller: false

#swiftmailer:
#    delivery_address: me@example.com
