imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    session:
        save_path: /dev/shm/powerline/%kernel.environment%

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            channels: [!event]
        push:
            type:  stream
            path:  %kernel.logs_dir%/push_%kernel.environment%.log
            level: debug
            channels: [push]
        slack:
            type: slack
            token: '%slack_logger_token%'
            channel: "#errors"
            level: error

assetic:
    use_controller: false

nelmio_api_doc:
    name: Civix API documentation

#swiftmailer:
#    delivery_address: me@example.com
