imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
        collect: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_sqlite_db: true
    authentication:
        username: "admin"
        password: "admin"
#    query:
#        max_query_count: 1

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     '/%kernel.cache_dir%/powerline-server-test.db'

parameters:
    sunlightapi_token: ~
    cicero_login: ~
    cicero_password: ~
    ciceroapi_class: Civix\CoreBundle\Service\CiceroCalls
    hostname: api-test.powerli.ne
    old_sound_rabbit_mq.fallback.class: Civix\CoreBundle\Test\FallbackProducer

civix_core:
    mailgun_client: mailgun.test_client
    mailgun_public_client: mailgun.test_client

vich_uploader:
    storage: '@civix_core.storage.array'

monolog:
    handlers:
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            channels: [!event]
        push:
            type: 'null'
        slack:
            type: 'null'

security:
    firewalls:
        superuser_security_area:
            http_basic:

bazinga_geocoder:
    default_provider: array

old_sound_rabbit_mq:
    debug: true
    enable_collector: false
    sandbox: true