parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     powerline
    database_user:     root
    database_password: ~

    mailer_transport:  mail
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    mailer_from:       "support@powerli.ne"
    mailer_beta_access_recipient: ~

    locale:            en
    secret:            secretsecret

    amazon_s3.key: ''
    amazon_s3.secret: ''
    amazon_s3.region: us-east-1
    amazon_s3.bucket: devpowerline
    amazon_s3.url: /

    amazon_sns.android_arn: 'arn:aws:sns:eu-west-1:863632456175:app/GCM/powerline_android_debug'
    amazon_sns.ios_arn: 'arn:aws:sns:eu-west-1:863632456175:app/APNS/powerline_ios_debug'

    recaptcha_public_key:   here_is_your_public_key
    recaptcha_private_key:  here_is_your_private_key
    recaptcha_secure:       false
    recaptcha_locale_key:   kernel.default_locale
    recaptcha_enabled:      true

    cicero_login: login
    cicero_password: password

    android_api_key: android_api_key
    android_app: app_key

    ios_is_sanbox: true
    ios_pem_path: app/Resources/certs
    ios_passphrase: passphrase

    sunlightapi_token: ~

    stripe_api_key:  sk_test_vpedTPsiXZZ8SSwS4isZzHWw
    stripe_publishable_key:  pk_test_QUgSE3ZhORW9yoDuCkMjnaA2
    stripe_referral_code: 1STMONTH

    domain: powerli.ne
    hostname: api.powerli.ne
    scheme: 'http'

    rabbitmq_connections:
        default:
            host: 'localhost'
            port: 5672
            user: 'guest'
            password: 'guest'
            vhost: '/'
            lazy: true

    mailgun_public: public_key
    mailgun_private: private_key

    auto_invite_group_name: 'Powerline Powerusers'
    imgix.domain:  powerline-dev.imgix.net

    default_api_version: 1

    facebook_client_id: xxx
    facebook_client_secret: yyy

    slack_logger_token: 'xoxp'

    one_signal.app_id: xxx
    one_signal.app_auth_key: xxx
    one_signal.user_auth_key: xxx