civix_api:
    resource: "@CivixApiBundle/Controller/"
    type:     annotation
    prefix:   /api
    defaults: { _format: 'json' }

civix_api_v2:
    resource: "@CivixApiBundle/Controller/V2/"
    type:     annotation
    prefix:   /api/v2
    defaults: { _format: 'json', version: "2" }

civix_api_public:
    resource: "@CivixApiBundle/Controller/PublicApi"
    type:     annotation
    prefix:   /api-public
    defaults: { _format: 'json' }

civix_front_default:
    resource: "@CivixFrontBundle/Controller"
    type: annotation
    prefix:   /

civix_front_superuser_login_check:
    path:  /admin/login_check

civix_superuser_logout:
    path:  /admin/logout

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-doc
    defaults: { view: default }

NelmioSwaggerApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
    prefix:   /swagger
    defaults: { view: default }