_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-doc
    defaults: { view: default }

NelmioSwaggerApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
    prefix:   /swagger
    defaults: { view: default }