jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Civix\CoreBundle\Entity\Superuser:
            algorithm: sha512
            encode-as-base64: false
            iterations: 473
        Civix\CoreBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: false
            iterations: 473

    providers:
        superuser:
            entity: { class: CivixCoreBundle:Superuser, property: username }
        mobileuser:
            entity: { class: CivixCoreBundle:User, property: username }

    firewalls:
        superuser_anonymous:
            pattern: ^/superuser/login$
            anonymous: ~
        superuser_security_area:
            pattern: ^/superuser/
            provider: superuser
            security: true
            form_login:
                check_path: /superuser/login_check
                login_path: /superuser/login
                csrf_provider: form.csrf_provider
                intention: superuser_authentication
            logout:
                path: /superuser/logout
                target: /superuser

        public_api:
            pattern: ^/api-public/
            anonymous: ~

        mobileuser_login:
            pattern: ^/api/secure/login$
            provider: mobileuser
            form-login:
                login_path: /api/secure/login
                check_path: /api/secure/login
                username_parameter: username
                password_parameter: password
                require_previous_session: false
                success_handler: civix_api.security.authentication_success_handler
                failure_handler: civix_api.security.authentication_failure_handler

        mobileuser_anonymous:
            pattern: ^/api/secure/
            anonymous: ~

        mobileuser_security_area:
            pattern: ^/api/
            stateless: ~
            oauth:
                login_path: /api/v2/security
                check_path: /api/v2/login_check
                resource_owners:
                    facebook: "/api/v2/security/facebook"
                oauth_user_provider:
                    service: api.security.user_provider
                require_previous_session: false
                success_handler: civix_api.security.authentication_success_handler
                failure_handler: civix_api.security.authentication_failure_handler
            security: true
            bearer_token: true
            provider: mobileuser

        leader_api_login:
            pattern: ^/api-leader/sessions/$
            anonymous: ~

        leader_api_secure_area:
            pattern: ^/api-leader/
            security: true
            bearer_token: true
            provider: mobileuser

        other_area:
            pattern: ^/
            anonymous: ~