services:
    civix_front.navbar_menu_builder:
        class: Civix\FrontBundle\Menu\MenuBuilder
        arguments: [ '@knp_menu.factory', '@security.authorization_checker' ]

    civix_front.navbar_main_menu:
        class: Knp\Menu\MenuItem
        factory: [ '@civix_front.navbar_menu_builder', createMainMenu ]
        tags:
            - { name: knp_menu.menu, alias: frontendNavbar }

    civix_front.navbar_manage_menu:
        class: Knp\Menu\MenuItem
        factory: [ '@civix_front.navbar_menu_builder', createManageMenu ]
        tags:
            - { name: knp_menu.menu, alias: manageMenu }

    Civix\FrontBundle\Controller\SecurityController:
        class: Civix\FrontBundle\Controller\SecurityController
        arguments: ['@doctrine.orm.entity_manager']