services:
    Civix\ApiBundle\Controller\V2\Group\LinkController:
        class: Civix\ApiBundle\Controller\V2\Group\LinkController
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    Civix\ApiBundle\Controller\V2\GroupLinksController:
        class: Civix\ApiBundle\Controller\V2\GroupLinksController
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    Civix\ApiBundle\Controller\V2\Group\BannerController:
        class: Civix\ApiBundle\Controller\V2\Group\BannerController
        arguments:
            - '@civix_core.group_manager'
            - '@civix_core.service.avatar_manager'
            - '@form.factory'

    Civix\ApiBundle\Controller\V2\Group\TagController:
        class: Civix\ApiBundle\Controller\V2\Group\TagController
        arguments: ['@civix_core.group_manager']

    Civix\ApiBundle\Controller\V2\GroupTagsController:
        class: Civix\ApiBundle\Controller\V2\GroupTagsController
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    Civix\ApiBundle\Controller\V2\DeviceController:
        class: Civix\ApiBundle\Controller\V2\DeviceController
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@security.token_storage'