services:
    Civix\ApiBundle\Controller\V2\Group\LinkController:
        class: Civix\ApiBundle\Controller\V2\Group\LinkController
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    Civix\ApiBundle\Controller\V2\GroupLinksController:
        class: Civix\ApiBundle\Controller\V2\GroupLinksController
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    Civix\ApiBundle\Controller\V2\Group\BannerController:
        class: Civix\ApiBundle\Controller\V2\Group\BannerController
        arguments:
            - '@civix_core.group_manager'
            - '@civix_core.service.avatar_manager'
            - '@form.factory'

    Civix\ApiBundle\Controller\V2\Group\TagController:
        class: Civix\ApiBundle\Controller\V2\Group\TagController
        arguments: ['@civix_core.group_manager']

    Civix\ApiBundle\Controller\V2\GroupTagsController:
        class: Civix\ApiBundle\Controller\V2\GroupTagsController
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    Civix\ApiBundle\Controller\V2\DeviceController:
        class: Civix\ApiBundle\Controller\V2\DeviceController
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@form.factory'
            - '@security.token_storage'

    Civix\ApiBundle\Controller\V2_2\PostCommentsController:
        class: Civix\ApiBundle\Controller\V2_2\PostCommentsController
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

    Civix\ApiBundle\Controller\V2_2\PostCommentController:
        class: Civix\ApiBundle\Controller\V2_2\PostCommentController
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

    Civix\ApiBundle\Controller\V2_2\UserPetitionCommentsController:
        class: Civix\ApiBundle\Controller\V2_2\UserPetitionCommentsController
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

    Civix\ApiBundle\Controller\V2_2\UserPetitionCommentController:
        class: Civix\ApiBundle\Controller\V2_2\UserPetitionCommentController
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

    Civix\ApiBundle\Controller\V2_2\PollCommentsController:
        class: Civix\ApiBundle\Controller\V2_2\PollCommentsController
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

    Civix\ApiBundle\Controller\V2_2\PollCommentController:
        class: Civix\ApiBundle\Controller\V2_2\PollCommentController
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

    Civix\ApiBundle\Controller\V2_2\Group\PostController:
        class: Civix\ApiBundle\Controller\V2_2\Group\PostController
        arguments:
            - '@civix_core.post_manager'
            - '@form.factory'
            - '@security.token_storage'

    Civix\ApiBundle\Controller\V2_2\Group\UserPetitionController:
        class: Civix\ApiBundle\Controller\V2_2\Group\UserPetitionController
        arguments:
            - '@civix_core.user_petition_manager'
            - '@form.factory'
            - '@security.token_storage'
