services:
    civix_api.form_extension.disable_csrf_extension:
        class: Civix\ApiBundle\Form\Extension\DisableCSRFExtension
        arguments: ['@request_stack']
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    civix_api.form_type.subscription_type:
        class: Civix\ApiBundle\Form\Type\SubscriptionType
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: form.type, alias: Civix\ApiBundle\Form\Type\SubscriptionType }

    civix_api.form_type.avatar_type:
        class: Civix\ApiBundle\Form\Type\EncodedFileType
        arguments: ['@civix_core.content_converter']
        tags:
            - { name: form.type, alias: Civix\ApiBundle\Form\Type\AvatarType }
