services:
    civix_core.tld_extract:
        class: LayerShifter\TLDExtract\Extract
        arguments:
            - ~
            - ~
            - !php/const:LayerShifter\TLDExtract\Extract::MODE_ALLOW_ICCAN

    civix_core.rabbit.push_queue:
        class: Civix\CoreBundle\Service\RabbitMQCallback\PushQueue
        arguments:
            - [ "@civix_core.push_sender", "@civix_core.representative_manager" ]
            - "@logger"