services:
    civix_core.tld_extract:
        class: LayerShifter\TLDExtract\Extract
        arguments:
            - ~
            - ~
            - !php/const:LayerShifter\TLDExtract\Extract::MODE_ALLOW_ICCAN

    civix_core.rabbit.push_queue:
        class: Civix\CoreBundle\Service\RabbitMQCallback\PushQueue
        arguments:
            - [ "@civix_core.push_sender", "@civix_core.representative_manager" ]
            - "@logger"

    civix_core.rabbit.async_event_consumer:
        class: Civix\CoreBundle\Service\RabbitMQCallback\AsyncEventConsumer
        arguments: ['@event_dispatcher', '@logger']

    civix_core.image_manager:
        class: Intervention\Image\ImageManager
        arguments:
            - { driver: gd }

    civix_core.cicero_api:
        class: Civix\CoreBundle\Service\CiceroApi
        arguments:
            - '@civix_core.cicero_calls'
            - '@doctrine.orm.entity_manager'
            - '@civix_core.congress_api'
            - '@civix_core.openstates_api'
            - '@civix_core.content_converter'
            - '@event_dispatcher'

    civix_core.converter_source.base64:
        class: Civix\Component\ContentConverter\Source\Base64

    civix_core.converter_source.url:
        class: Civix\Component\ContentConverter\Source\Url
        arguments:
            - [ '%imgix.domain%' ]

    civix_core.content_converter:
        class: Civix\Component\ContentConverter\Converter
        arguments:
            - "@civix_core.converter_source.base64"
            - "@civix_core.converter_source.url"

    civix_core.data_collector.rabbit_mqdata_collector:
        class: Civix\CoreBundle\DataCollector\RabbitMQDataCollector
        arguments: ['@old_sound_rabbit_mq.async_event_producer']
        tags:
            - { name: data_collector, id: rabbit_mq }

    civix_core.service.user_local_group_manager:
        class: Civix\CoreBundle\Service\UserLocalGroupManager
        arguments:
            - '@geocoder'
            - '@doctrine.orm.entity_manager'
            - '@civix_core.repository.group_repository'
            - '@logger'

#    civix_core.uploader.metadata.file_locator:
#        class: Metadata\Driver\FileLocator
#        public: false
#        arguments: [[]]
#        decorates: vich_uploader.metadata.file_locator