- name: install python modules for ansible
  tags: setup
  apt: pkg=python-pycurl state=latest

- name: install curl
  tags: setup
  apt: pkg=curl state=latest

- name: php repo
  tags: setup
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: install project dependencies
  apt: pkg={{ item }} state=latest
  tags: setup
  with_items:
    - nginx
    - php7.0
    - php7.0-common
    - php7.0-fpm
    - php7.0-cli
    - php7.0-curl
    - php7.0-gd
    - php7.0-mysql
    - php7.0-sqlite3
    - php7.0-intl
    - php7.0-bcmath
    - php7.0-xml
    - php7.0-mbstring
    - supervisor
    - rabbitmq-server
