- name: copy server deb package
  tags: deploy
  copy: src=../../build/current.deb dest=/srv/current.deb owner=root group=root mode=644

- name: stop nginx
  tags: deploy
  service: name=nginx state=stopped

- name: stop php5-fpm
  tags: deploy
  service: name=php5-fpm state=stopped

- name: stop supervisor payments
  tags: deploy
  supervisorctl: name=civix_payments state=stopped

- name: install / update server package
  tags: deploy
  command: /usr/bin/dpkg -i /srv/current.deb

- name: use app_dev.php
  tags: deploy
  command: mv /srv/{{ project }}/web/app_dev.php /srv/{{ project }}/web/app.php
  when: dev_env is defined

- name: remove app_dev.php
  tags: deploy
  command: rm /srv/{{ project }}/web/app_dev.php
  when: dev_env is not defined

- name: start php5-fpm
  tags: deploy
  service: name=php5-fpm state=started

- name: start nginx
  tags: deploy
  service: name=nginx state=started

- name: start supervisor payments
  tags: deploy
  supervisorctl: name=civix_payments state=started

- name: reset application cache
  become_user: civix
  tags: deploy
  command: /srv/{{ project }}/bin/console cache:clear --env={% if dev_env is defined %}dev{% else %}prod{% endif %} --no-debug