services:
    civix_core.event_listener.discount_code_subscriber:
        class: Civix\CoreBundle\EventListener\DiscountCodeSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@civix_core.stripe'
            - '%stripe_referral_code%'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.report_subscriber:
        class: Civix\CoreBundle\EventListener\ReportSubscriber
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.geocoder_subscriber:
        class: Civix\CoreBundle\EventListener\GeocoderSubscriber
        arguments: ['@geocoder']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.async_event_listener:
        class: Civix\CoreBundle\EventListener\AsyncEventListener
        arguments: ['@old_sound_rabbit_mq.async_event_producer']
        tags:
            - { name: kernel.event_listener, event: async_event.dispatch }