services:
    civix_core.event_listener.discount_code_subscriber:
        class: Civix\CoreBundle\EventListener\DiscountCodeSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@civix_core.stripe'
            - '%stripe_referral_code%'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.report_subscriber:
        class: Civix\CoreBundle\EventListener\ReportSubscriber
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.geocoder_subscriber:
        class: Civix\CoreBundle\EventListener\GeocoderSubscriber
        arguments: ['@geocoder', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.karma_subscriber:
        class: Civix\CoreBundle\EventListener\KarmaSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@civix_core.karma_repository'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.async_event_listener:
        class: Civix\CoreBundle\EventListener\AsyncEventListener
        arguments:
            - '@old_sound_rabbit_mq.async_event_producer'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: async_event.dispatch }

    civix_core.event_listener.user_local_group_subscriber:
            class: Civix\CoreBundle\EventListener\UserLocalGroupSubscriber
            arguments:
                - '@civix_core.service.user_local_group_manager'
            tags:
                - { name: kernel.event_subscriber }

    civix_core.event_listener.user_avatar_subscriber:
        class: Civix\CoreBundle\EventListener\AvatarSubscriber
        arguments: ['@civix_core.image_manager', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.openstates_subscriber:
        class: Civix\CoreBundle\EventListener\OpenstatesSubscriber
        arguments: ['@civix_core.openstates_api']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.cicero_subscriber:
        class: Civix\CoreBundle\EventListener\CiceroSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@civix_core.cicero_api'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.push_subscriber:
        class: Civix\CoreBundle\EventListener\PushSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@imgix.url_builder'
            - '%hostname%'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.pro_publica_subscriber:
        class: Civix\CoreBundle\EventListener\ProPublicaSubscriber
        arguments:
            - '@civix_core.propublica'
            - '@civix_core.pro_publica_representative_populator'
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.mention_subscriber:
        class: Civix\CoreBundle\EventListener\MentionSubscriber
        arguments:
            - '@civix_core.repository.user_repository'
            - '@civix_core.social_activity_manager'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.social_activity_subscriber:
        class: Civix\CoreBundle\EventListener\SocialActivitySubscriber
        arguments:
            - '@civix_core.social_activity_manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.amqp_subscriber:
        class: Civix\CoreBundle\EventListener\AMQPSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.thumbnail_subscriber:
        class: Civix\CoreBundle\EventListener\ThumbnailSubscriber
        arguments:
            - '@civix.thumbnail_generator.thumbnail_generator'
            - '@vich_uploader.upload_handler'
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }

    civix_api.event_listener.petition_metadata_listener:
        class: Civix\CoreBundle\EventListener\MetadataSubscriber
        arguments:
            - "@http.client"
            - "@civix_core.service.htmlmetadata_parser"
            - "@civix_core.tld_extract"
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }