services:
    civix_core.event_listener.discount_code_subscriber:
        class: Civix\CoreBundle\EventListener\DiscountCodeSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@civix_core.stripe'
            - '%stripe_referral_code%'
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.report_subscriber:
        class: Civix\CoreBundle\EventListener\ReportSubscriber
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.geocoder_subscriber:
        class: Civix\CoreBundle\EventListener\GeocoderSubscriber
        arguments: ['@geocoder', '@logger']
        tags:
            - { name: kernel.event_subscriber }

    civix_core.event_listener.karma_subscriber:
        class: Civix\CoreBundle\EventListener\KarmaSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@civix_core.karma_repository'
        tags:
            - { name: kernel.event_subscriber }    civix_core.event_listener.async_event_listener:
        class: Civix\CoreBundle\EventListener\AsyncEventListener
        arguments: ['@old_sound_rabbit_mq.async_event_producer']
        tags:
            - { name: kernel.event_listener, event: async_event.dispatch }

    civix_core.event_listener.user_local_group_subscriber:
            class: Civix\CoreBundle\EventListener\UserLocalGroupSubscriber
            arguments:
                - '@geocoder'
                - '@doctrine.orm.entity_manager'
                - '@civix_core.repository.group_repository'
                - '@civix_core.group_manager'
                - '@logger'
            tags:
                - { name: kernel.event_subscriber }